-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 21:59:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taller
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taller
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller` DEFAULT CHARACTER SET utf8mb4 ;
USE `taller` ;

-- -----------------------------------------------------
-- Table `taller`.`TBL_tipo_de_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_tipo_de_identificacion` (
  `idTBL_tipo_de_cedula` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTBL_tipo_de_cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_nacionalidad` (
  `idTBL_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nacionalidad` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTBL_nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_tipo_de_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_tipo_de_personas` (
  `idTBL_tipo_de_personas` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTBL_tipo_de_personas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_generos` (
  `idTBL_generos` INT NOT NULL,
  `tipo_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_generos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_personas` (
  `idTBL_personas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `fecha_creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizado` TIMESTAMP NULL,
  `TBL_tipo_de_identificacion_idTBL_tipo_de_cedula` INT NOT NULL,
  `TBL_nacionalidad_idTBL_nacionalidad` INT NOT NULL,
  `TBL_tipo_de_personas_idTBL_tipo_de_personas` INT NOT NULL,
  `TBL_generos_idTBL_generos` INT NOT NULL,
  PRIMARY KEY (`idTBL_personas`, `TBL_tipo_de_identificacion_idTBL_tipo_de_cedula`, `TBL_nacionalidad_idTBL_nacionalidad`, `TBL_tipo_de_personas_idTBL_tipo_de_personas`, `TBL_generos_idTBL_generos`),
  INDEX `fk_TBL_personas_TBL_tipo_de_identificacion1_idx` (`TBL_tipo_de_identificacion_idTBL_tipo_de_cedula` ASC) ,
  INDEX `fk_TBL_personas_TBL_nacionalidad1_idx` (`TBL_nacionalidad_idTBL_nacionalidad` ASC) ,
  INDEX `fk_TBL_personas_TBL_tipo_de_personas1_idx` (`TBL_tipo_de_personas_idTBL_tipo_de_personas` ASC) ,
  INDEX `fk_TBL_personas_TBL_generos1_idx` (`TBL_generos_idTBL_generos` ASC) ,
  CONSTRAINT `fk_TBL_personas_TBL_tipo_de_identificacion1`
    FOREIGN KEY (`TBL_tipo_de_identificacion_idTBL_tipo_de_cedula`)
    REFERENCES `taller`.`TBL_tipo_de_identificacion` (`idTBL_tipo_de_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_personas_TBL_nacionalidad1`
    FOREIGN KEY (`TBL_nacionalidad_idTBL_nacionalidad`)
    REFERENCES `taller`.`TBL_nacionalidad` (`idTBL_nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_personas_TBL_tipo_de_personas1`
    FOREIGN KEY (`TBL_tipo_de_personas_idTBL_tipo_de_personas`)
    REFERENCES `taller`.`TBL_tipo_de_personas` (`idTBL_tipo_de_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_personas_TBL_generos1`
    FOREIGN KEY (`TBL_generos_idTBL_generos`)
    REFERENCES `taller`.`TBL_generos` (`idTBL_generos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_clientes` (
  `idTBL_clientes` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio_cliente` DATE NOT NULL,
  `nr_pedidos` VARCHAR(45) NOT NULL,
  `TBL_personas_idTBL_personas` INT(11) NOT NULL,
  `licencia_de_conducir` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_clientes`, `TBL_personas_idTBL_personas`),
  INDEX `fk_TBL_cliente_TBL_personas1_idx` (`TBL_personas_idTBL_personas` ASC) ,
  CONSTRAINT `fk_TBL_cliente_TBL_personas1`
    FOREIGN KEY (`TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_personas` (`idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_tipos_de_vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_tipos_de_vehiculos` (
  `idTBL_tipo_de_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_tipo_de_vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_vehiculo` (
  `idTBL_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `TBL_clientes_idTBL_clientes` INT NOT NULL,
  `TBL_tipo_de_vehiculo_idTBL_tipo_de_vehiculo` INT NOT NULL,
  PRIMARY KEY (`idTBL_vehiculo`, `TBL_tipo_de_vehiculo_idTBL_tipo_de_vehiculo`),
  INDEX `fk_TBL_vehiculo_TBL_clientes1_idx` (`TBL_clientes_idTBL_clientes` ASC) ,
  INDEX `fk_TBL_vehiculo_TBL_tipo_de_vehiculo1_idx` (`TBL_tipo_de_vehiculo_idTBL_tipo_de_vehiculo` ASC) ,
  CONSTRAINT `fk_TBL_vehiculo_TBL_clientes1`
    FOREIGN KEY (`TBL_clientes_idTBL_clientes`)
    REFERENCES `taller`.`TBL_clientes` (`idTBL_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_vehiculo_TBL_tipo_de_vehiculo1`
    FOREIGN KEY (`TBL_tipo_de_vehiculo_idTBL_tipo_de_vehiculo`)
    REFERENCES `taller`.`TBL_tipos_de_vehiculos` (`idTBL_tipo_de_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_marca` (
  `idTBL_marca` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_marca` INT(11) NOT NULL,
  `modelo` VARCHAR(250) NOT NULL,
  `TBL_vehiculo_idTBL_vehiculo` INT NOT NULL,
  PRIMARY KEY (`idTBL_marca`, `TBL_vehiculo_idTBL_vehiculo`),
  INDEX `fk_TBL_marca_TBL_vehiculo1_idx` (`TBL_vehiculo_idTBL_vehiculo` ASC) ,
  CONSTRAINT `fk_TBL_marca_TBL_vehiculo1`
    FOREIGN KEY (`TBL_vehiculo_idTBL_vehiculo`)
    REFERENCES `taller`.`TBL_vehiculo` (`idTBL_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_categoria` (
  `idTBL_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('herramientas', 'repuestos') NOT NULL,
  PRIMARY KEY (`idTBL_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_proveedor` (
  `idTBL_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `rif` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `TBL_personas_idTBL_personas` INT(11) NOT NULL,
  PRIMARY KEY (`idTBL_proveedor`, `TBL_personas_idTBL_personas`),
  INDEX `fk_TBL_proveedor_TBL_personas1_idx` (`TBL_personas_idTBL_personas` ASC) ,
  CONSTRAINT `fk_TBL_proveedor_TBL_personas1`
    FOREIGN KEY (`TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_personas` (`idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_pedidos` (
  `tbV_pedidos` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_orden` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `TBL_proveedor_idTBL_proveedor` INT(11) NOT NULL,
  PRIMARY KEY (`tbV_pedidos`, `TBL_proveedor_idTBL_proveedor`),
  INDEX `fk_TBL_pedidos_TBL_proveedor1_idx` (`TBL_proveedor_idTBL_proveedor` ASC) ,
  CONSTRAINT `fk_TBL_pedidos_TBL_proveedor1`
    FOREIGN KEY (`TBL_proveedor_idTBL_proveedor`)
    REFERENCES `taller`.`TBL_proveedor` (`idTBL_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_modelos` (
  `idTBL_modelos` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_modelos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_inventario` (
  `idTBL_inventario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio` DOUBLE(20,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `precio_por_servicio` DECIMAL NOT NULL,
  `TBL_modelos_idTBL_modelos` INT NOT NULL,
  `TBL_categoria_idTBL_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`idTBL_inventario`),
  INDEX `fk_TBL_producto_TBL_modelos1_idx` (`TBL_modelos_idTBL_modelos` ASC) ,
  INDEX `fk_TBL_producto_TBL_categoria1_idx` (`TBL_categoria_idTBL_categoria` ASC) ,
  CONSTRAINT `fk_TBL_producto_TBL_modelos1`
    FOREIGN KEY (`TBL_modelos_idTBL_modelos`)
    REFERENCES `taller`.`TBL_modelos` (`idTBL_modelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_producto_TBL_categoria1`
    FOREIGN KEY (`TBL_categoria_idTBL_categoria`)
    REFERENCES `taller`.`TBL_categoria` (`idTBL_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_roles` (
  `idTBL_roles` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_usuario` (
  `idtbL_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `estado` ENUM('Active', 'Inactive') NOT NULL,
  `fecha_creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizado` TIMESTAMP NULL,
  `TBL_personas_idTBL_personas` INT(11) NOT NULL,
  `TBL_roles_idTBL_roles` INT NOT NULL,
  PRIMARY KEY (`idtbL_usuario`, `TBL_personas_idTBL_personas`, `TBL_roles_idTBL_roles`),
  INDEX `fk_TBL_usuario_TBL_personas1_idx` (`TBL_personas_idTBL_personas` ASC) ,
  INDEX `fk_TBL_usuario_TBL_roles1_idx` (`TBL_roles_idTBL_roles` ASC) ,
  CONSTRAINT `fk_TBL_usuario_TBL_personas1`
    FOREIGN KEY (`TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_personas` (`idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_usuario_TBL_roles1`
    FOREIGN KEY (`TBL_roles_idTBL_roles`)
    REFERENCES `taller`.`TBL_roles` (`idTBL_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_devolucion` (
  `idTBL_devolucion` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_producto` DOUBLE(20,2) NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `cambio_o_devolucion` ENUM('cambio', 'devolucion') NOT NULL,
  PRIMARY KEY (`idTBL_devolucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_factura` (
  `idTBL_factura` INT NOT NULL AUTO_INCREMENT,
  `costo_total` DOUBLE(20,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `TBL_clientes_idTBL_clientes` INT NOT NULL,
  `TBL_clientes_TBL_personas_idTBL_personas` INT(11) NOT NULL,
  PRIMARY KEY (`idTBL_factura`),
  INDEX `fk_TBL_factura_TBL_clientes1_idx` (`TBL_clientes_idTBL_clientes` ASC, `TBL_clientes_TBL_personas_idTBL_personas` ASC) ,
  CONSTRAINT `fk_TBL_factura_TBL_clientes1`
    FOREIGN KEY (`TBL_clientes_idTBL_clientes` , `TBL_clientes_TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_clientes` (`idTBL_clientes` , `TBL_personas_idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_TipoDeServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_TipoDeServicio` (
  `idTBL_TipoDeServicio` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idTBL_TipoDeServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Servicios` (
  `idTBL_Servicios` INT NOT NULL AUTO_INCREMENT,
  `TBL_TipoDeServicio_idTBL_TipoDeServicio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `TBL_usuario_idtbL_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idTBL_Servicios`, `TBL_TipoDeServicio_idTBL_TipoDeServicio`, `TBL_usuario_idtbL_usuario`),
  INDEX `fk_TBL_Servicios_TBL_TipoDeServicio1_idx` (`TBL_TipoDeServicio_idTBL_TipoDeServicio` ASC) ,
  INDEX `fk_TBL_Servicios_TBL_usuario1_idx` (`TBL_usuario_idtbL_usuario` ASC) ,
  CONSTRAINT `fk_TBL_Servicios_TBL_TipoDeServicio1`
    FOREIGN KEY (`TBL_TipoDeServicio_idTBL_TipoDeServicio`)
    REFERENCES `taller`.`TBL_TipoDeServicio` (`idTBL_TipoDeServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Servicios_TBL_usuario1`
    FOREIGN KEY (`TBL_usuario_idtbL_usuario`)
    REFERENCES `taller`.`TBL_usuario` (`idtbL_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_CodigoArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_CodigoArea` (
  `idTBL_CodigoArea` INT NOT NULL AUTO_INCREMENT,
  `codigo_de_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_CodigoArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_estado` (
  `idTBL_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTBL_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_municipio` (
  `idTBL_municipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(200) NOT NULL,
  `TBL_estado_idTBL_estado` INT NOT NULL,
  PRIMARY KEY (`idTBL_municipio`, `TBL_estado_idTBL_estado`),
  INDEX `fk_TBL_municipio_TBL_estado1_idx` (`TBL_estado_idTBL_estado` ASC) ,
  CONSTRAINT `fk_TBL_municipio_TBL_estado1`
    FOREIGN KEY (`TBL_estado_idTBL_estado`)
    REFERENCES `taller`.`TBL_estado` (`idTBL_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_parroquias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_parroquias` (
  `idTBL_parroquias` INT NOT NULL AUTO_INCREMENT,
  `parroquia` VARCHAR(200) NOT NULL,
  `TBL_municipio_idTBL_municipio` INT NOT NULL,
  `TBL_municipio_TBL_estado_idTBL_estado` INT NOT NULL,
  PRIMARY KEY (`idTBL_parroquias`, `TBL_municipio_idTBL_municipio`, `TBL_municipio_TBL_estado_idTBL_estado`),
  INDEX `fk_TBL_parroquia_TBL_municipio1_idx` (`TBL_municipio_idTBL_municipio` ASC, `TBL_municipio_TBL_estado_idTBL_estado` ASC) ,
  CONSTRAINT `fk_TBL_parroquia_TBL_municipio1`
    FOREIGN KEY (`TBL_municipio_idTBL_municipio` , `TBL_municipio_TBL_estado_idTBL_estado`)
    REFERENCES `taller`.`TBL_municipio` (`idTBL_municipio` , `TBL_estado_idTBL_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_tipo_de_nro_telefonico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_tipo_de_nro_telefonico` (
  `idTBL_tipo_de_nro_telefonico` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_tipo_de_nro_telefonico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Telefonos` (
  `TBL_personas_idTBL_personas` INT(11) NOT NULL AUTO_INCREMENT,
  `TBL_CodigoArea_idTBL_CodigoArea` INT NOT NULL,
  `TBL_tipo_de_nro_telefonico_idTBL_tipo_de_nro_telefonico` INT NOT NULL,
  `numero_de_telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TBL_personas_idTBL_personas`, `TBL_CodigoArea_idTBL_CodigoArea`),
  INDEX `fk_TBL_CodigoArea_has_TBL_personas_TBL_personas1_idx` (`TBL_personas_idTBL_personas` ASC) ,
  INDEX `fk_TBL_CodigoArea_has_TBL_personas_TBL_CodigoArea1_idx` (`TBL_CodigoArea_idTBL_CodigoArea` ASC) ,
  INDEX `fk_TBL_Telefonos_TBL_tipo_de_nro_telefonico1_idx` (`TBL_tipo_de_nro_telefonico_idTBL_tipo_de_nro_telefonico` ASC) ,
  CONSTRAINT `fk_TBL_CodigoArea_has_TBL_personas_TBL_CodigoArea1`
    FOREIGN KEY (`TBL_CodigoArea_idTBL_CodigoArea`)
    REFERENCES `taller`.`TBL_CodigoArea` (`idTBL_CodigoArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_CodigoArea_has_TBL_personas_TBL_personas1`
    FOREIGN KEY (`TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_personas` (`idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Telefonos_TBL_tipo_de_nro_telefonico1`
    FOREIGN KEY (`TBL_tipo_de_nro_telefonico_idTBL_tipo_de_nro_telefonico`)
    REFERENCES `taller`.`TBL_tipo_de_nro_telefonico` (`idTBL_tipo_de_nro_telefonico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Direccion` (
  `TBL_personas_idTBL_personas` INT(11) NOT NULL AUTO_INCREMENT,
  `TBL_parroquias_idTBL_parroquias` INT NOT NULL,
  `TBL_parroquias_TBL_municipio_idTBL_municipio` INT NOT NULL,
  `TBL_parroquias_TBL_municipio_TBL_estado_idTBL_estado` INT NOT NULL,
  PRIMARY KEY (`TBL_personas_idTBL_personas`, `TBL_parroquias_idTBL_parroquias`, `TBL_parroquias_TBL_municipio_idTBL_municipio`, `TBL_parroquias_TBL_municipio_TBL_estado_idTBL_estado`),
  INDEX `fk_TBL_personas_has_TBL_municipio_TBL_personas1_idx` (`TBL_personas_idTBL_personas` ASC) ,
  INDEX `fk_TBL_Direccion_TBL_parroquias1_idx` (`TBL_parroquias_idTBL_parroquias` ASC, `TBL_parroquias_TBL_municipio_idTBL_municipio` ASC, `TBL_parroquias_TBL_municipio_TBL_estado_idTBL_estado` ASC) ,
  CONSTRAINT `fk_TBL_personas_has_TBL_municipio_TBL_personas1`
    FOREIGN KEY (`TBL_personas_idTBL_personas`)
    REFERENCES `taller`.`TBL_personas` (`idTBL_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Direccion_TBL_parroquias1`
    FOREIGN KEY (`TBL_parroquias_idTBL_parroquias` , `TBL_parroquias_TBL_municipio_idTBL_municipio` , `TBL_parroquias_TBL_municipio_TBL_estado_idTBL_estado`)
    REFERENCES `taller`.`TBL_parroquias` (`idTBL_parroquias` , `TBL_municipio_idTBL_municipio` , `TBL_municipio_TBL_estado_idTBL_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taller`.`TBL_devolucion_has_TBL_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_devolucion_has_TBL_pedidos` (
  `TBL_devolucion_idTBL_devolucion` INT NOT NULL AUTO_INCREMENT,
  `TBL_pedidos_tbV_pedidos` INT(11) NOT NULL,
  PRIMARY KEY (`TBL_devolucion_idTBL_devolucion`, `TBL_pedidos_tbV_pedidos`),
  INDEX `fk_TBL_devolucion_has_TBL_pedidos_TBL_devolucion1_idx` (`TBL_devolucion_idTBL_devolucion` ASC) ,
  INDEX `fk_TBL_devolucion_has_TBL_pedidos_TBL_pedidos1_idx` (`TBL_pedidos_tbV_pedidos` ASC) ,
  CONSTRAINT `fk_TBL_devolucion_has_TBL_pedidos_TBL_devolucion1`
    FOREIGN KEY (`TBL_devolucion_idTBL_devolucion`)
    REFERENCES `taller`.`TBL_devolucion` (`idTBL_devolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_devolucion_has_TBL_pedidos_TBL_pedidos1`
    FOREIGN KEY (`TBL_pedidos_tbV_pedidos`)
    REFERENCES `taller`.`TBL_pedidos` (`tbV_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Servicios_has_TBL_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Servicios_has_TBL_factura` (
  `TBL_Servicios_idTBL_Servicios` INT NOT NULL,
  `TBL_factura_idTBL_factura` INT NOT NULL,
  PRIMARY KEY (`TBL_Servicios_idTBL_Servicios`, `TBL_factura_idTBL_factura`),
  INDEX `fk_TBL_Servicios_has_TBL_factura_TBL_factura1_idx` (`TBL_factura_idTBL_factura` ASC) ,
  INDEX `fk_TBL_Servicios_has_TBL_factura_TBL_Servicios1_idx` (`TBL_Servicios_idTBL_Servicios` ASC) ,
  CONSTRAINT `fk_TBL_Servicios_has_TBL_factura_TBL_Servicios1`
    FOREIGN KEY (`TBL_Servicios_idTBL_Servicios`)
    REFERENCES `taller`.`TBL_Servicios` (`idTBL_Servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Servicios_has_TBL_factura_TBL_factura1`
    FOREIGN KEY (`TBL_factura_idTBL_factura`)
    REFERENCES `taller`.`TBL_factura` (`idTBL_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Servicios_has_TBL_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Servicios_has_TBL_producto` (
  `TBL_Servicios_idTBL_Servicios` INT NOT NULL AUTO_INCREMENT,
  `TBL_producto_idTBL_producto` INT(11) NOT NULL,
  PRIMARY KEY (`TBL_Servicios_idTBL_Servicios`, `TBL_producto_idTBL_producto`),
  INDEX `fk_TBL_Servicios_has_TBL_producto_TBL_producto1_idx` (`TBL_producto_idTBL_producto` ASC) ,
  INDEX `fk_TBL_Servicios_has_TBL_producto_TBL_Servicios1_idx` (`TBL_Servicios_idTBL_Servicios` ASC) ,
  CONSTRAINT `fk_TBL_Servicios_has_TBL_producto_TBL_Servicios1`
    FOREIGN KEY (`TBL_Servicios_idTBL_Servicios`)
    REFERENCES `taller`.`TBL_Servicios` (`idTBL_Servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Servicios_has_TBL_producto_TBL_producto1`
    FOREIGN KEY (`TBL_producto_idTBL_producto`)
    REFERENCES `taller`.`TBL_inventario` (`idTBL_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Diagnostico` (
  `idTBL_Diagnostico` INT NOT NULL AUTO_INCREMENT,
  `TBL_vehiculo_idTBL_vehiculo` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idTBL_Diagnostico`, `TBL_vehiculo_idTBL_vehiculo`),
  INDEX `fk_TBL_Diagnostico_TBL_vehiculo1_idx` (`TBL_vehiculo_idTBL_vehiculo` ASC) ,
  CONSTRAINT `fk_TBL_Diagnostico_TBL_vehiculo1`
    FOREIGN KEY (`TBL_vehiculo_idTBL_vehiculo`)
    REFERENCES `taller`.`TBL_vehiculo` (`idTBL_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_tipos_de_fallos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_tipos_de_fallos` (
  `idTBL_tipos_de_fallos` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_tipos_de_fallos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_Fallos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_Fallos` (
  `idTBL_Fallos` INT NOT NULL AUTO_INCREMENT,
  `TBL_Diagnostico_idTBL_Diagnostico` INT NOT NULL,
  `TBL_tipos_de_fallos_idTBL_tipos_de_fallos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_Fallos`, `TBL_Diagnostico_idTBL_Diagnostico`, `TBL_tipos_de_fallos_idTBL_tipos_de_fallos`),
  INDEX `fk_TBL_Fallos_TBL_Diagnostico1_idx` (`TBL_Diagnostico_idTBL_Diagnostico` ASC) ,
  INDEX `fk_TBL_Fallos_TBL_tipos_de_fallos1_idx` (`TBL_tipos_de_fallos_idTBL_tipos_de_fallos` ASC) ,
  CONSTRAINT `fk_TBL_Fallos_TBL_Diagnostico1`
    FOREIGN KEY (`TBL_Diagnostico_idTBL_Diagnostico`)
    REFERENCES `taller`.`TBL_Diagnostico` (`idTBL_Diagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Fallos_TBL_tipos_de_fallos1`
    FOREIGN KEY (`TBL_tipos_de_fallos_idTBL_tipos_de_fallos`)
    REFERENCES `taller`.`TBL_tipos_de_fallos` (`idTBL_tipos_de_fallos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_productos` (
  `idTBL_productos` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `cantidad_por_unidad` VARCHAR(45) NOT NULL,
  `TBL_inventario_idTBL_inventario` INT(11) NOT NULL,
  PRIMARY KEY (`idTBL_productos`, `TBL_inventario_idTBL_inventario`),
  INDEX `fk_TBL_productos_TBL_inventario1_idx` (`TBL_inventario_idTBL_inventario` ASC) ,
  CONSTRAINT `fk_TBL_productos_TBL_inventario1`
    FOREIGN KEY (`TBL_inventario_idTBL_inventario`)
    REFERENCES `taller`.`TBL_inventario` (`idTBL_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller`.`TBL_detalles_del_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller`.`TBL_detalles_del_pedido` (
  `TBL_productos_idTBL_productos` INT NOT NULL,
  `TBL_pedidos_tbV_pedidos` INT(11) NOT NULL,
  `precio_por_unidad` DECIMAL NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TBL_productos_idTBL_productos`, `TBL_pedidos_tbV_pedidos`),
  INDEX `fk_TBL_productos_has_TBL_pedidos_TBL_productos1_idx` (`TBL_productos_idTBL_productos` ASC) ,
  INDEX `fk_TBL_detalles_del_pedido_TBL_pedidos1_idx` (`TBL_pedidos_tbV_pedidos` ASC) ,
  CONSTRAINT `fk_TBL_productos_has_TBL_pedidos_TBL_productos1`
    FOREIGN KEY (`TBL_productos_idTBL_productos`)
    REFERENCES `taller`.`TBL_productos` (`idTBL_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_detalles_del_pedido_TBL_pedidos1`
    FOREIGN KEY (`TBL_pedidos_tbV_pedidos`)
    REFERENCES `taller`.`TBL_pedidos` (`tbV_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
