# Generated by Django 3.2.16 on 2022-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblGeneros',
            fields=[
                ('idtbl_generos', models.IntegerField(db_column='idTBL_generos', primary_key=True, serialize=False)),
                ('tipo_genero', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNacionalidad',
            fields=[
                ('idtbl_nacionalidad', models.AutoField(db_column='idTBL_nacionalidad', primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPersonas',
            fields=[
                ('idtbl_personas', models.AutoField(db_column='idTBL_personas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=45)),
                ('fecha_creado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRoles',
            fields=[
                ('idtbl_roles', models.AutoField(db_column='idTBL_roles', primary_key=True, serialize=False)),
                ('tipo_de_rol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoDeIdentificacion',
            fields=[
                ('idtbl_tipo_de_cedula', models.AutoField(db_column='idTBL_tipo_de_cedula', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_tipo_de_identificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoDePersonas',
            fields=[
                ('idtbl_tipo_de_personas', models.AutoField(db_column='idTBL_tipo_de_personas', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_tipo_de_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('idtbl_usuario', models.AutoField(db_column='idtbL_usuario', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=8)),
                ('fecha_creado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_usuario',
                'managed': False,
            },
        ),
    ]
