# Generated by Django 4.1.3 on 2022-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblgeneros',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblnacionalidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblpersonas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblroles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbltipodeidentificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbltipodepersonas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblusuario',
            options={},
        ),
    ]
